### ISSUE TITLE
logged in deleted User

### ISSUE THREAD

**Issue by N8boy** [Codetana/TangoBB#33]
If a user is logged in and the User is deleted in the database he get's many Errors. 

It should be checked if there is a User like the Session and if not the session should be killed.

**Comment by N8boy** [comment]
@jtpox can you do this?

**Comment by jtpox** [comment]
Should be fixed now.

**Comment by N8boy** [comment]
94b528bd213599bf909b5651956e84d3a46d9f51 fixed this
