### ISSUE TITLE
Incorrect display Cyrillic

### ISSUE THREAD

**Issue by Nyarl** [Codetana/TangoBB#35]
Can you add to forum Cyrillic letters? At the moment it works bad. For example, there are weird displaying threads in the address bar (i pinned screenshot below).
![c3eca06ae7db0a267b7e0e13e4141aa6](https://cloud.githubusercontent.com/assets/2233889/5221468/e3496dd0-7683-11e4-814d-2590ff2de8c5.png)

And in the topic names there are incorrect encoding.
![330278f9767cae0e3755d83a96264c10](https://cloud.githubusercontent.com/assets/2233889/5221478/1a38e03c-7684-11e4-8748-1e3bbda853a5.png)

If you fix it, i can translate Iko to the Ukrainian, Russian and Belorussian languages. Waiting for your reply.

**Comment by N8boy** [comment]
Should be fixed in 1.5.0.
The change from mysqli to PDO fixed this by accident
