### ISSUE TITLE
Installation recommends 777 file system permission

### ISSUE THREAD

**Issue by fgeek** [Codetana/TangoBB#41]
Installation recommends 777 file system permission for file applications/config.php, which is insecure in shared working environments. Group and others should not need write permissions for PHP files.

**Comment by N8boy** [comment]
Which version?

**Comment by fgeek** [comment]
Current Git version.

**Comment by N8boy** [comment]
Okay we will talk about this. Thanks for your report :)

**Comment by cxdy** [comment]
Someone fixed this some time ago but didn't update the issue. 

It's now at 666.
