### ISSUE TITLE
Brand New Installation

### ISSUE THREAD

**Issue by shadow-neo** [Codetana/TangoBB#42]
Parse error: syntax error, unexpected end of file in /home/u270142336/public_html/forum/applications/classes/template.php(305) : eval()'d code on line 266

(Edited by Cody for formatting)

**Comment by N8boy** [comment]
A litte bit more information would be great.
Which version?
What did you do that the error is shown?

**Comment by shadow-neo** [comment]
I installed the newest version and when I delete the install folder it shows.

**Comment by cxdy** [comment]
What version of PHP are you running?

**Comment by shadow-neo** [comment]
MySQL Version: 5.1.61

**Comment by cxdy** [comment]
PHP, not MySQL.

**Comment by cxdy** [comment]
At the top, in the purple, it says 'PHP Version x.x.x'

**Comment by shadow-neo** [comment]
Oh, my bad. PHP Version: 5.5

**Comment by cxdy** [comment]
Hmm.
Looks like Blade syntax is fucking up.

**Comment by cxdy** [comment]
The only thing I can recommend is to try reinstalling with a stable release, like 1.4.1.
https://github.com/Codetana/TangoBB/releases/tag/1.4.1

If you want to try it, feel free to install 1.5.0-A3.
https://github.com/Codetana/TangoBB/releases/tag/1.5.0-A3

**Comment by N8boy** [comment]
@shadow-neo any news? Is 1.4.1 working? And what about 1.5.0?

**Comment by cxdy** [comment]
Any news on this?

**Comment by N8boy** [comment]
No answer so closed.
