### ISSUE TITLE
What happen to Iko and demo?

### ISSUE THREAD

**Issue by axisdos** [Codetana/TangoBB#43]
What happen to the Iko software. I thought TangoBB is outdated. When will you have the live demo version? Thanks

**Comment by cxdy** [comment]
Iko has been rebranded back to TangoBB.

As for the live demo, no idea.

**Comment by N8boy** [comment]
Like @cxdy says Iko (former TangoBB) has been rebranded back to TangoBB because of popluar demand.

A live demo will be uploaded in the next weeks. Mostly to get rid of all bugs.
We decided to delay the release of 1.5 because we want to add more features in before. For example polls.

**Comment by sapioit** [comment]
Still waiting for a demo...

**Comment by N8boy** [comment]
I think a demo will take a bit. In the last time there were some 'events' which will change TangoBB extremely. I'm not in the team anymore, only @jtpox is working on this. And he will give the bb a new theme engine what might can take a bit. 
I split apart from TangoBB to create a new forum IkoBB, and we are creating a complete new core and system. So which way you want to go, you have to wait sadly. But we are doing our best to release a demo as fast as possible

**Comment by sapioit** [comment]
Thanks for noticing me!
Good luck with it!
